/**
 * Variables for Development Environment
 */

variable "project_id" {
  description = "Project id, references existing project if `project_create` is null."
  type        = string
  default     = "southend-test-pharmacy"
}

variable "region" {
  type        = string
  description = "The region where resources will be deployed."
  default     = "us-central1"
}

variable "cloud_run_invoker" {
  type        = string
  description = "IAM member authorized to access the end-point (for example, 'user:YOUR_IAM_USER' for only you or 'allUsers' for everyone)"
  default     = "allUsers"
}

variable "cloudsql_password" {
  type        = string
  description = "CloudSQL password (will be randomly generated by default)"
  default     = null
  sensitive   = true
}

variable "connector" {
  type        = string
  description = "Existing VPC serverless connector to use if not creating a new one"
  default     = null
}

variable "create_connector" {
  type        = bool
  description = "Should a VPC serverless connector be created or not"
  default     = true
}

variable "ip_ranges" {
  description = "CIDR blocks: VPC serverless connector, Private Service Access(PSA) for CloudSQL, CloudSQL VPC"
  type = object({
    connector = string
    psa       = string
    sql_vpc   = string
  })
  default = {
    connector = "10.11.0.0/28"
    psa       = "10.63.0.0/24"
    sql_vpc   = "10.48.0.0/20"
  }
}

variable "prefix" {
  description = "Unique prefix used for resource names. Not used for project if 'project_create' is null."
  type        = string
  default     = "sp-test"
}

variable "principals" {
  description = "List of users to give rights to (CloudSQL admin, client and instanceUser, Logging admin, Service Account User and TokenCreator), eg 'user@domain.com'."
  type        = list(string)
  default     = ["samuel.beuran@alliahealth.co"]
}

variable "project_create" {
  description = "Provide values if project creation is needed, uses existing project if null. Parent is in 'folders/nnn' or 'organizations/nnn' format."
  type = object({
    billing_account_id = string
    parent             = string
  })
  default = null
}

variable "wordpress_image" {
  type        = string
  description = "Image to run with Cloud Run, starts with \"gcr.io\" or \"REGION-docker.pkg.dev\""
  default     = "mirror.gcr.io/library/wordpress"
}

variable "wordpress_port" {
  type        = number
  description = "Port for the Wordpress image"
  default     = 80
}

